# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'AsyncDisplayKit'
pod 'pop'
pod 'SVWebViewController'
pod 'ZLBalancedFlowLayout'
pod 'ZLSwipeableView'
pod 'ReactiveUI'
pod 'SwiftyJSON'
pod 'TTTAttributedLabel'


link_with 'Zhixuan Lai', 'Zhixuan LaiTests'


use_frameworks!